import { Router } from 'express';
import { adminRouter } from './admin.routes.js';
import { analyzeRouter } from './analyze.routes.js';
import { barcodeRouter } from './barcode.routes.js';
import { authRouter } from './auth.routes.js';
import { foodRouter } from './food.routes.js';
import { goalRouter } from './goal.routes.js';
import { healthRouter } from './health.routes.js';
import { mealRouter } from './meal.routes.js';
import { profileRouter } from './profile.routes.js';
import { settingsRouter } from './settings.routes.js';
import { workoutRouter } from './workout.routes.js';
import { weightRouter } from './weight.routes.js';
import { insightsRouter } from './insights.routes.js';
import { waterRouter } from './water.routes.js';
import { savedMealRouter } from './savedmeal.routes.js';
import { recipeRouter } from './recipe.routes.js';
import { fastingRouter } from './fasting.routes.js';
import { analyzeTextRouter } from './analyze-text.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/meals', mealRouter);
apiRouter.use('/goal', goalRouter);
apiRouter.use('/profile', profileRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/workouts', workoutRouter);
apiRouter.use('/weight', weightRouter);
apiRouter.use('/insights', insightsRouter);
apiRouter.use('/water', waterRouter);
apiRouter.use('/saved-meals', savedMealRouter);
apiRouter.use('/recipes', recipeRouter);
apiRouter.use('/fasting', fastingRouter);
apiRouter.use('/analyze-text', analyzeTextRouter);
apiRouter.use('/foods', foodRouter);
apiRouter.use('/analyze-food', analyzeRouter);
apiRouter.use('/barcode', barcodeRouter);
apiRouter.use('/admin', adminRouter);
